# Visit https://github.com/lowlighter/metrics#-documentation for full reference
---
name: Metrics
on:
  # Schedule updates (each hour)
  schedule:
    - cron: "0 * * * *"
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push:
    branches: ["master", "main"]
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # Install required dependencies
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io jq
          sudo systemctl start docker
          sudo systemctl enable docker
          sudo usermod -aG docker $USER

      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          # The following scopes are required:
          #  - public_access (default scope)
          # The following additional scopes may be required:
          #  - read:org      (for organization related metrics)
          #  - read:user     (for user related data)
          #  - read:packages (for some packages related data)
          #  - repo          (optional, if you want to include
          #                   private repositories)
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: 0xrinegade
          template: classic
          base: header, activity, community, repositories, metadata
          base_indepth: true
          repositories_affiliations: organization_member
          config_timezone: Europe/Moscow
          plugin_isocalendar: true
          plugin_isocalendar_duration: half-year
          plugin_lines: true
          plugin_lines_history_limit: 10
          plugin_lines_repositories_limit: 40
          plugin_lines_sections: base
          plugin_lines_skipped: ""
          plugin_repositories: true
          plugin_repositories_order: featured, pinned, starred, random
          plugin_repositories_random: 5
          plugin_repositories_starred: 11
          plugin_repositories_affiliations: organization_member
          plugin_repositories_skipped: ""
      - uses: lowlighter/metrics@latest
        with:
          filename: metrics.plugin.habits.facts.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_habits: true
          plugin_habits_facts: true
          plugin_habits_charts: true
          config_timezone: Europe/Moscow
